Temporary images refactor
ashotvdovychenko/tangerine-web pull request #27
Opened 2023-09-28 19:57 UTC by Pagendera

2023-09-28 20:27 UTC, neodavis requested changes
Please, resolve comments bellow + replace pictures with compressed versions (images load is so slow for now)

2023-09-28 20:27 UTC, neodavis commented on src/main.js
> +document.querySelector('#puncake').src=puncake
leave spaces between property name and "=" operator

2023-09-28 20:27 UTC, neodavis commented on src/style.css
> +
get rid off unnecessary breaks at the end of the file (always leave only 1 empty line)

2023-09-28 20:27 UTC, neodavis commented on src/main.js
> +import puncake from '../assets/puncake.png'
please, always provide semi-columns on the end of the line (keep code clean, check other places for possible improvement)

2023-09-29 01:31 UTC, ashotvdovychenko approved these changes
I have no questions

2023-09-29 09:26 UTC, neodavis approved these changes

2023-09-29 09:38 UTC, merged